services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=taquilla_parque
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/db:/var/lib/mysql
      - ./db/schema_and_seed.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
